[settings]
experimental = true
plugin_autoupdate_last_check_duration = '1 week'
trusted_config_paths = [
    '~/dev',
]
python_compile = true

[tools]
python = "3.12.1"
node = "18"
pnpm = "8"
aws-iam-authenticator = "0.6.11"
kubectx = "latest"
kubectl = "latest"
awscli = "latest"
terraform = "latest"
watchexec = "latest"
